AM_QMQ/Controllers/DoacaoController.cs
using AM_QMQ.Models;
using AM_QMQ.UnitsOfWork;
using AM_QMQ.ViewsModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_QMQ.Controllers
{
    public class DoacaoController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Doacao()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Doacao(DonationViewModel model)
        {
            List<Person> person = (List<Person>)_unit.PersonRepository.SearchFor(p => p.UserName == User.Identity.Name);
            var donation = new Donation
            {
                Description = model.Description,
                Launch = DateTime.Today,
                PersonId = person[0].PersonId,
                Situation = model.Situation,
                Status = model.Status,
                Title = model.Title
            };
            _unit.DonationRepository.Add(donation);
            _unit.Save();

            TempData["msg"] = "Doação Cadastrada!";
            return View();
        }

        public FilePathResult Image()
        {
            string filename = Request.Url.AbsolutePath.Replace("/home/image", "");
            string contentType = "";
            var filePath = new FileInfo(Server.MapPath("~/App_Data") + filename);

            var index = filename.LastIndexOf(".") + 1;
            var extension = filename.Substring(index).ToUpperInvariant();

            // Fix for IE not handling jpg image types
            contentType = string.Compare(extension, "JPG") == 0 ? "image/jpeg" : string.Format("image/{0}", extension);

            return File(filePath.FullName, contentType);
        }

        [HttpPost]
        public ContentResult UploadFiles()
        {
            var r = new List<UploadFilesResult>();

            foreach (string file in Request.Files)
            {
                HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                if (hpf.ContentLength == 0)
                    continue;

                string savedFileName = Path.Combine(Server.MapPath("~/App_Data"), User.Identity.Name+"."+Path.GetFileName(hpf.FileName));
                hpf.SaveAs(savedFileName);

                r.Add(new UploadFilesResult()
                {
                    Name = hpf.FileName,
                    Length = hpf.ContentLength,
                    Type = hpf.ContentType
                });
            }
            return Content("{\"name\":\"" + r[0].Name + "\",\"type\":\"" + r[0].Type + "\",\"size\":\"" + string.Format("{0} bytes", r[0].Length) + "\"}", "application/json");
        }

        public ActionResult Imagem()
        {
            Image();
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

AM_QMQ/Controllers/PessoaController.cs
using AM_QMQ.Models;
using AM_QMQ.UnitsOfWork;
using AM_QMQ.ViewsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AM_QMQ.Controllers
{
    public class PessoaController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(PersonViewModel model)
        {
            if (model.Password != model.Password2)
            {
                ModelState.AddModelError("Password", "Senhas Não Conferem");
                return View();
            }
            if (_unit.PersonRepository.SearchFor(p => p.UserName == model.UserName).Count != 0)
            {
                ModelState.AddModelError("UserName", "Nome de Usuário já Cadastrado");
                return View();
            }
            if (_unit.PersonRepository.SearchFor(p => p.Email == model.Email).Count != 0)
            {
                ModelState.AddModelError("Email", "Email já Cadastrado");
                return View();
            }
            if (ModelState.IsValid)
            {
                if (model.Type == "I")
                {
                    List<Phone> list = new List<Phone>();
                    list.Add(new Phone());
                    list.Add(new Phone());
                    var individual = new PersonIndividual
                    {
                        PersonId = model.PersonId,
                        Status = "A",
                        FiledDate = DateTime.Today,
                        Email = model.Email,
                        Password = model.Password,
                        Type = "I",
                        UserName = model.UserName,
                        BirthDate = DateTime.Parse("11/11/1800"),
                        Phones = list,
                        Address = new Address()
                    };
                    _unit.PersonRepository.Add(individual);
                    _unit.Save();
                }

                if (model.Type == "L")
                {
                    List<Phone> list = new List<Phone>();
                    list.Add(new Phone());
                    var legal = new PersonLegal
                    {
                        PersonId = model.PersonId,
                        Status = "A",
                        FiledDate = DateTime.Today,
                        Email = model.Email,
                        Password = model.Password,
                        Type = "L",
                        UserName = model.UserName,
                        Phones = list,
                        Address = new Address()
                    };
                    _unit.PersonRepository.Add(legal);
                    _unit.Save();
                }

                TempData["msg"] = "Usuário Cadastrado!";
                return View();
            }
            else
            {
                return View();
            }
        }

        public ActionResult Editar()
        {
            List<Person> person = (List<Person>)_unit.PersonRepository.SearchFor(p => p.UserName == User.Identity.Name);
            if (person[0].Type == "I")
            {
                return RedirectToAction("EditarFisica");
            }
            else
            {
                return RedirectToAction("EditarJuridica");
            }
        }

        [HttpGet]
        public ActionResult EditarFisica()
        {
            // Recupera a pessoa através do nome de usuário do Cookie
            List<Person> person = (List<Person>)_unit.PersonRepository.SearchFor(m => m.UserName == User.Identity.Name);
            
            // Recupera a pessoa física
            PersonIndividual individual = _unit.IndividualRepository.SearchById(person[0].PersonId);
            
            // Telefones 
            List<Phone> list = individual.Phones.ToList();           
            string p1 = list[0].Ddd + "" + list[0].Number;
            string p2 = list[1].Ddd + "" + list[1].Number;

            // Dados da Pessoa
            PersonViewModel p = new PersonViewModel();
            p.PersonId = individual.PersonId;
            p.Email = individual.Email;
            p.FiledDate = individual.FiledDate;
            p.UserName = individual.UserName;
            p.Password = individual.Password;
            p.Type = individual.Type;
            p.Status = individual.Status;
            p.Ranking = individual.Ranking;
            
            // Dados do Endereço
            p.Address = new AddressViewModel();
            p.Address.Addition = individual.Address.Addition;
            p.Address.AddressId = individual.Address.AddressId;
            p.Address.Cep = individual.Address.Cep;
            p.Address.Number = individual.Address.Number;
            p.Address.Patio = individual.Address.Patio;
            // Verifica se já houve alteração, para não buscar valor nulo
            if (individual.Address.City != 0)
            {
                p.Address.District = individual.Address.District.Name;
                p.Address.City = individual.Address.District.City.Name;
                p.Address.State = individual.Address.District.City.State.Abb;
            }
            else
            {
                p.Address.City = "";
                p.Address.District = "";
                p.Address.State = "";
            }
          
            // Dados pessoa física
            IndividualViewModel model = new IndividualViewModel
            {
                Person = p,
                Name = individual.Name,
                Cpf = individual.Cpf,
                Rg = individual.Rg,
                BirthDate = individual.BirthDate,
                Phone1 = p1,
                Phone2 = p2
            };
            return View(model);
             
        }

        [HttpPost]
        public ActionResult EditarFisica(IndividualViewModel model)
        {
           // if (ModelState.IsValid)
          //  {
                // Recupera a pessoa através do nome de usuário do Cookie
                List<PersonIndividual> individual = (List<PersonIndividual>)_unit.IndividualRepository.SearchFor(p => p.UserName == User.Identity.Name);
                
                // Telefone
                List<Phone> list = individual[0].Phones.ToList();
                list[0].Ddd = Convert.ToInt32(model.Phone1.Substring(1, 2));
                list[0].Number = Convert.ToInt32(model.Phone1.Substring(4).Replace("-", ""));
                list[1].Ddd = Convert.ToInt32(model.Phone2.Substring(1, 2));
                list[1].Number = Convert.ToInt32(model.Phone2.Substring(4).Replace("-",""));

                // Endereço
                individual[0].Address.Patio = model.Person.Address.Patio;
                individual[0].Address.Number = model.Person.Address.Number;
                individual[0].Address.Cep = model.Person.Address.Cep;
                individual[0].Address.Addition = model.Person.Address.Addition;

                // Código da cidade caso ela não possua bairro para poder recuperar o endereço
                List<City> cities = (List<City>)_unit.CityRepository.SearchFor(c => c.Name == model.Person.Address.City && c.State.Abb == model.Person.Address.State);
                int cityId = cities[0].CityId;
                individual[0].Address.City = cityId;

                // Bairro do endereço
                List<District> districts = (List<District>)_unit.DistrictRepository.SearchFor(d => d.Name == model.Person.Address.District && d.City.Name == model.Person.Address.City);
                int districtId = districts[0].DistrictId;
                individual[0].Address.District = districts[0];

                // Dados pessoa fisica
                individual[0].BirthDate = model.BirthDate;
                individual[0].Cpf = model.Cpf;
                individual[0].Name = model.Name;
                individual[0].Rg = model.Rg;
                individual[0].Phones = list;

                // Faz e comita as alterações
                _unit.IndividualRepository.Update(individual[0]);
                _unit.AddressRepository.Update(individual[0].Address);
                _unit.Save();
                TempData["msg"] = "Usuário Alterado!";
                return View();            
            //}
          /*  else
            {
                TempData["msg"] = ModelState.;
                return View();
            }*/
        }

        [HttpGet]
        public ActionResult EditarJuridica()
        {
            // Recupera a pessoa através do nome de usuário do Cookie
            List<Person> person = (List<Person>)_unit.PersonRepository.SearchFor(m => m.UserName == User.Identity.Name);

            // Recupera a pessoa jurídica
            PersonLegal legal = _unit.LegalRepository.SearchById(person[0].PersonId);

            // Telefones 
            List<Phone> list = legal.Phones.ToList();
            string p1 = list[0].Ddd + "" + list[0].Number;

            // Dados da Pessoa
            PersonViewModel p = new PersonViewModel();
            p.PersonId = legal.PersonId;
            p.Email = legal.Email;
            p.FiledDate = legal.FiledDate;
            p.UserName = legal.UserName;
            p.Password = legal.Password;
            p.Type = legal.Type;
            p.Status = legal.Status;
            p.Ranking = legal.Ranking;

            // Dados do Endereço
            p.Address = new AddressViewModel();
            p.Address.Addition = legal.Address.Addition;
            p.Address.AddressId = legal.Address.AddressId;
            p.Address.Cep = legal.Address.Cep;
            p.Address.Number = legal.Address.Number;
            p.Address.Patio = legal.Address.Patio;
            // Verifica se já houve alteração, para não buscar valor nulo

AM_QMQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/content/themes/base/all.css" rel="stylesheet" />
    <link href="~/content/themes/base/jquery.ui.all.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery.inputmask/jquery.inputmask.js"></script>
    <script src="~/scripts/jquery.maskedinput.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>

    <link href="~/content/owlcarousel/owl.carousel.css" rel="stylesheet" />
    <link href="~/content/owlcarousel/owl.theme.css" rel="stylesheet" />
    <link href="~/content/owlcarousel/owl.transitions.css" rel="stylesheet" />
    <script src="~/scripts/owl.carousel.min.js"></script>

    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="~/Content/jQuery.FileUpload/css/jquery.fileupload.css">
    <link rel="stylesheet" href="~/Content/jQuery.FileUpload/css/jquery.fileupload-ui.css">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quem Me Quer", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Doador <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Logar", "Logar", "Pessoa")</li>
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "Pessoa")</li>
                            <li>@Html.ActionLink("ListarPessoa", "Listar", "Pessoa")</li>
                        </ul>                     
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Editar", "Editar", "Pessoa")
                        }
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Doação", "Doacao", "Doacao")
                        }
                    </li>
                </ul>

                <div class="navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="navbar-text">@User.Identity.Name</span>
                        @Html.ActionLink("Sair", "Deslogar", "Pessoa", null, new { @class = "btn btn-danger btn-sm navbar-btn" })
                    }
                    else
                    {
                        @Html.ActionLink("Entrar", "Logar", "Pessoa", null, new { @class = "btn btn-success btn-sm navbar-btn", style = "margin-right: 5px;" })
                        @Html.ActionLink("Registre-se", "Cadastrar", "Pessoa", null, new { @class = "btn btn-info btn-sm navbar-btn" })
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


</body>
</html>